/* Title: Database example schema */
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS Campuses
(
  CAMPUS_NAME TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS Books
(
    ISBN13 INTEGER PRIMARY KEY NOT NULL,
    TITLE TEXT NOT NULL,
    AUTHOR TEXT,
    PUBLISHER TEXT,
    RELEASE_DATE DATE,
    COVER TEXT,
    CAMPUS INTEGER,
    AVAILABLE_STOCK INTEGER,
    TOTAL_STOCK INTEGER,
    FOREIGN KEY(CAMPUS) REFERENCES Campuses(rowid)
);
CREATE TABLE IF NOT EXISTS Librarians
(
    UUID INTEGER PRIMARY KEY NOT NULL,
    LIB_PASSHASH TEXT NOT NULL,
    LIB_FIRSTNAME TEXT NOT NULL,
    LIB_LASTNAME TEXT NOT NULL,
    LIB_CAMPUS INTEGER,
    FOREIGN KEY(LIB_CAMPUS) REFERENCES Campuses(rowid)
);
CREATE TABLE IF NOT EXISTS Rentees
(
    MATRICULE INTEGER PRIMARY KEY NOT NULL,
    RENTEE_FIRSTNAME TEXT NOT NULL,
    RENTEE_LASTNAME TEXT NOT NULL,
    RENTEE_DEGREE TEXT
);

CREATE TABLE IF NOT EXISTS Genres
(
    GENRE_NAME TEXT NOT NULL,
    GENRE_DESCRIPTION TEXT
);

/* Associations */

CREATE TABLE IF NOT EXISTS BOOKS_GENRES
(
    BOOK INTEGER NOT NULL,
    GENRE INTEGER NOT NULL,
    FOREIGN KEY (BOOK) REFERENCES Books(ISBN13),
    FOREIGN KEY (GENRE) REFERENCES Genres(rowid),
    UNIQUE (BOOK,GENRE)
);
CREATE TABLE IF NOT EXISTS IN_POSSESSION
(
    RENTEE INTEGER NOT NULL,
    BOOK INTEGER NOT NULL,
    RENT_DATE DATETIME NOT NULL,
    UNIQUE(BOOK,RENTEE,RENT_DATE),
    FOREIGN KEY (RENTEE) REFERENCES Rentees(MATRICULE),
    FOREIGN KEY (BOOK) REFERENCES BOOKS(ISBN13)
);
CREATE TABLE IF NOT EXISTS TRANSACTIONS
(
    TRANS_DATE DATETIME NOT NULL,
    LIBRARIAN INTEGER NOT NULL,
    RENTEE INTEGER NOT NULL,
    BOOK INTEGER NOT NULL,
    TRANS_TYPE BOOLEAN NOT NULL
);