CREATE TABLE IF NOT EXISTS CAMPUSES
(
    CAMPUS_NAME TEXT UNIQUE NOT NULL
);
CREATE TABLE IF NOT EXISTS BOOKS
(
    ISBN13       INTEGER NOT NULL,
    TITLE        TEXT    NOT NULL,
    AUTHOR       TEXT,
    PUBLISHER    TEXT,
    RELEASE_DATE DATE,
    COVER        TEXT,
    CAMPUS       INTEGER,
    AVAILABLE    BOOLEAN,
    FOREIGN KEY (CAMPUS) REFERENCES CAMPUSES (rowid)
);
CREATE TABLE IF NOT EXISTS LIBRARIANS
(
    UUID          INTEGER PRIMARY KEY NOT NULL,
    LIB_PASSHASH  TEXT                NOT NULL,
    LIB_FIRSTNAME TEXT                NOT NULL,
    LIB_LASTNAME  TEXT                NOT NULL,
    LIB_CAMPUS    INTEGER,
    FOREIGN KEY (LIB_CAMPUS) REFERENCES CAMPUSES (rowid)
);
CREATE TABLE IF NOT EXISTS ADMINS
(
    UUID        INTEGER PRIMARY KEY NOT NULL,
    PASSHASH    TEXT                NOT NULL,
    DISPLAYNAME TEXT                NOT NULL
);
CREATE TABLE IF NOT EXISTS RENTEES
(
    MATRICULE        INTEGER PRIMARY KEY NOT NULL,
    RENTEE_FIRSTNAME TEXT                NOT NULL,
    RENTEE_LASTNAME  TEXT                NOT NULL,
    RENTEE_DEGREE    TEXT
);

CREATE TABLE IF NOT EXISTS GENRES
(
    GENRE_NAME        TEXT NOT NULL,
    GENRE_DESCRIPTION TEXT
);

/* Associations */

CREATE TABLE IF NOT EXISTS BOOKS_GENRES
(
    BOOK  INTEGER NOT NULL,
    GENRE INTEGER NOT NULL,
    FOREIGN KEY (BOOK) REFERENCES BOOKS (ROWID),
    FOREIGN KEY (GENRE) REFERENCES GENRES (ROWID),
    UNIQUE (BOOK, GENRE)
);
CREATE TABLE IF NOT EXISTS INVENTORY
(
    RENTEE    INTEGER  NOT NULL,
    BOOK      INTEGER  NOT NULL,
    RENT_DATE DATETIME NOT NULL,
    UNIQUE (BOOK, RENTEE, RENT_DATE),
    FOREIGN KEY (RENTEE) REFERENCES RENTEES (MATRICULE),
    FOREIGN KEY (BOOK) REFERENCES BOOKS (ROWID)
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS
(
    TRANS_DATE DATETIME NOT NULL,
    LIBRARIAN  INTEGER  NOT NULL,
    RENTEE     INTEGER  NOT NULL,
    BOOK       INTEGER  NOT NULL,
    TRANS_TYPE BOOLEAN  NOT NULL,
    FOREIGN KEY (LIBRARIAN) REFERENCES LIBRARIANS (UUID),
    FOREIGN KEY (BOOK) REFERENCES BOOKS (ROWID),
    FOREIGN KEY (RENTEE) REFERENCES RENTEES (MATRICULE)
);

INSERT INTO CAMPUSES
VALUES ('El Kseur');
INSERT INTO CAMPUSES
VALUES ('Targa');
INSERT INTO CAMPUSES
VALUES ('Aboudaou');

INSERT INTO LIBRARIANS
VALUES (12345, '543939322DEFJFER', 'Bim', 'Le libraire', (SELECT ROWID FROM CAMPUSES WHERE CAMPUS_NAME = 'El Kseur'))